layout: sidebar
style: dark
encoding: UTF-8

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
  - jekyll-sitemap
  - jekyll-feed

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

categories:
  research:
    - research/_posts/vinn.md

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 15
  exclude:
    archived: false
    forks: true
    projects:
    - SridharPandian.github.io
    - Deep-Learning-Competition-Spring-2022
    - Service-Us
    - Decentralized-Voting-Application
    - Custom-Linux-Drivers
    - Note-Creator

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: sripan172
  twitter: pandian_sridhar
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: sridhar-pandian
  scholar: w8ceznMAAAAJ
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # unsplash: your_username
  # vk: your_username
  website: http://sridharpandian.github.io
  # youtube: your_username

topics:
  - name: Robotics
    web_url: https://github.com/topics/robotics
    image_url: assets/robot.png
  
  - name: Deep Learning
    web_url: https://github.com/topics/deep-learning
    image_url: assets/ai.png

  - name: Computer Vision
    web_url: https://github.com/topics/deep-learning
    image_url: assets/cv.png